# See https://pre-commit.com for more information
default_install_hook_types:
  - pre-commit
  - commit-msg
repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.6.0
    hooks:
      - id: conventional-pre-commit
        stages:
          - commit-msg
  - repo: https://github.com/nozaq/pre-commit-deno
    rev: 0.1.0
    hooks:
      - id: deno-lint
        args:
          - "-"
      - id: deno-fmt
