name: Build and Publish

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - uses: pre-commit/action@v3.0.1

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install dependencies
        run: deno install

      - name: Check lint
        run: deno lint

      - name: Check format
        run: deno fmt --check

      - name: Type checking
        run: deno task check

  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build \
            --platform linux/amd64 \
            --provenance false \
            --target production \
            -t deno-hono-nest-example:latest \
            .
