name: Build

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install dependencies
        run: deno install

      - name: Check lint
        run: deno lint

      - name: Check format
        run: deno fmt --check

      - name: Type checking
        run: deno task check

      - name: Cache dependencies
        run: deno task compile
